### ISSUE TITLE
Is tag of foreignkey  just add foreign key while not add constraint for the time being?

### ISSUE THREAD

**Issue by edl7878** [go-gorm/gorm#1971]
### What version of Go are you using (`go version`)?
go version go1.10.2 windows/amd64

### Which database and its version are you using?
PostgreSQL 10

```golang

type User struct {
	gorm.Model
	Name string
}

type Product struct {
	gorm.Model
	Code  string
	Price uint
	UserID uint
	User  User 
	

```

as code up lists

as table created in db, the result:

user_id is created.

but the foreign key constraint of  is not created.

what I want to confirm are:

1、Is tag of foreignkey  just add foreign key while not add constraint for the time being?
2、Are Gorm relate and association functions just “soft association” between struct objs while not db entities？

Thanks for your answer.

**Comment by dalu** [comment]
Documentation is severely lacking in this regard.
Then there are 2 kinds of docs.

What is the definitive guide to GORM associations?

For instance 2 models:

```go
type Community struct {
	Model
	OwnerID     uuid.UUID    `gorm:"type:uuid" json:"owner_id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Locale      string       `json:"locale,omitempty"`
	Containers  []*Container `gorm:"foreignkey:community_id;association_foreignkey:id" json:"containers"`
}

type Container struct {
	Model
	CommunityID uuid.UUID `gorm:"type:uuid" json:"community_id"`
	Title       string    `json:"title"`
	Forums      []*Forum  `gorm:"foreignkey:container_id;association_foreignkey:id" json:"forums"`
}
```

Those are the 2 top models.

According to documentation this should create the hard association in the database. http://gorm.io/docs/has_many.html well to be fair it doesn't state that. Documentation is lacking. Well the foreign keys are not created. When I create them manually, I have to create it on the reference_id side's table and it creates an index. So maybe gorm not doing this is a bug?

I usually don't use SQL anymore so this is my.. well 1st time I'm using it for an actual serious project. And the only reason I am is because manual association creation in mongodb/go is rather cumbersome.

@jinzhu can we have an answer?

**Comment by dalu** [comment]
#450 original issue
