### ISSUE TITLE
db.Save

### ISSUE THREAD

**Issue by lslz627** [go-gorm/gorm#2242]
https://github.com/jinzhu/gorm/blob/master/main.go#L439

i want to know why there has a FirstOrCreate operator when saving is as update action?

![image](https://user-images.githubusercontent.com/18484770/50623091-6c934500-0f4d-11e9-9096-2ee9882025fb.png)

thank you! @jinzhu

**Comment by shackra** [comment]
See this commit https://github.com/jinzhu/gorm/commit/02f6ae3c4ed211472b0492cee02ff3ddfdc1830d

**Comment by kejiro** [comment]
This could create an issue, especially since it's not mentioned anywhere. 

For example.
A row is fetched from the database, doing some processing on it, and then saved.
During the processing part, another connection is removing the row for some reason.
Then the row is saved, and since it no longer exists in the DB, it is created again which could cause inconsistencies since the other connection assumes it's removed. Especially if the row in question is depending on another row that also have been removed.

Sure, it can be avoided by doing another select within a transaction just before the update, but that would be 2 round-trips to the DB instead of failing to update and let the developer decide what to do. 

One solution could be to have it as an option which behaviour the developer wants.

**Comment by bsbak** [comment]
YEAH! Me to just want to update, no create if not exists.

**Comment by ansima** [comment]
> Me to just want to update, no create if not exists.

And no create if it did not change. When I try to update a row that has no changes, a duplicate row is created. A workaround is to have an `UpdatedAt` column which is always set to the current time (with fine enough granularity).
