### ISSUE TITLE
the result of searching  data by db.Find() method is null value, why is it?

### ISSUE THREAD

**Issue by LKSimon** [go-gorm/gorm#2379]
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
)

func main() {
	dsn := "sqlserver://SA:****@localhost:1433?database=TestDB"
	db, err := gorm.Open("mssql", dsn)
	//db.LogMode(true)
	if nil != err {
		fmt.Println(err)
		return
	}

	result := []convert_info_s{}
	if err := db.Table("convert_info").Find(&result).Error; nil != err {
		fmt.Println(err)
		return
	}
	fmt.Println("result = ", result)

	result2 := []m_opch_s{}
	if err := db.Table("convert_info").Select("Id").First(&result2).Error; nil != err {
		fmt.Println(err)
		return
	}
	fmt.Println("result2 = ", result2)
}

type convert_info_s struct {
	Id         int64
	From_type  string
	From_value string
	To_value   string
}

type m_opch_s struct {
	Id int64 `gorm: "column: id"`
}

**Comment by fwhezfwhez** [comment]
can you provide your data type in your database?
I guess the problem occurred because of points below:
1. `column:id`, not `column: id`  there should be no space.
2. point 1 shows your database is called `id`, but you select `Id`, mssql maybe case-sensitive.
3. your conver_info hasn't mapped by tag like
4.never use snake case and camel case together, hard read.
```go
type convert_info_s struct {
Id int64           `gorm:"column:id"`
From_type string  `gorm:"column:from_type"`
From_value string  `gorm:"column:from_value"`
To_value string  `gorm:"column:to_value"`
}
``` 
"
type m_opch_s struct {
Id int64 gorm: "column: id"
}
"
