### ISSUE TITLE
Pooling/Concurrency

### ISSUE THREAD

**Issue by arianitu** [go-gorm/gorm#246]
database/sql maintains an internal pool that can be safely accessed concurrently. Is gorm safe to be accessed via multiple goroutines? 

If I call gorm.Open(), is it pooled?

**Comment by ThreeBearsDan** [comment]
Very good question and answer. I encounter the same question when I use gorm.

**Comment by Carrotman42** [comment]
I suspect the fact that pooling wasn't working is that TCP KeepAlive was not set properly on the GCE VMs hosting the databases and/or on the local clients connecting to these databases. On Cloud SQL we explicitly tune KeepAlive to prevent transient breaks of long-lived database connections so that pooling will work effectively. I don't think this is specifically a Go or database/sql problem (unless there's more data to the contrary, in which case I'd be happy to help debug).

**Comment by m0onspell** [comment]
@badoet, thank you, I don't know why, but setting `db.DB().SetMaxIdleConns(0)` boosted performance by many times for me. I am able to handle much more requests per second now.

**Comment by SulanthaM** [comment]
> I suspect the fact that pooling wasn't working is that TCP KeepAlive was not set properly on the GCE VMs hosting the databases and/or on the local clients connecting to these databases. On Cloud SQL we explicitly tune KeepAlive to prevent transient breaks of long-lived database connections so that pooling will work effectively. I don't think this is specifically a Go or database/sql problem (unless there's more data to the contrary, in which case I'd be happy to help debug).

can you explain how you tune cloud SQL keep alive? I'm using cloud run to access cloud SQL and I'm seeing random (but often) aborting connection errors. (I do defer close db in my app). 

Any suggestions would be helpful.
