### ISSUE TITLE
Insert data into database using interface{}

### ISSUE THREAD

**Issue by achu1612** [go-gorm/gorm#2775]
In my use case, I have to insert data into a table. I am unaware of the schema of the table. I have the data in json format. Is there any way, I can insert the data in the table with out defining any structs because the data and tables will change very frequently.

I have tried this, but it did not work.

`data := {"uid":"1234", "email_id":"abc@gmail.com"}`

`var insertData interface{}`
`_ = json.Unmarshal([]byte(data), &insertData )`
`db.Table("USR_DATA").Create(&insert)`

**Comment by imdatngo** [comment]
That's not possible with Gorm, you have to use a struct to create new record. Otherwise, try to build the raw SQL sentence yourself.

By the way, it sounds weird to me that the table schema would be changed "very frequently" when you're using Gorm, which is an ORM lib for the relational database (SQL)... You might want to use the non-relational database (NoSQL) instead.

**Comment by achu1612** [comment]
The schema would change "very frequently" for the application. I meant I have to store the data in different database tables and I have no idea about the schema of the tables.

**Comment by zaneli** [comment]
> try to build the raw SQL sentence yourself.

Agree.

I think Gorm (and any other ORM libraries) is not suitable for such use case.
