### ISSUE TITLE
tried docs example for foreign key, doesn't work.

### ISSUE THREAD

**Issue by medyagh** [go-gorm/gorm#2831]
followed the docs for has manyhttp://gorm.io/docs/has_many.html for sqlilite

```
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)


type User struct {
	Id          string
	Name        string
	CreditCards []CreditCard `gorm:"FOREIGNKEY:user_id;ASSOCIATION_FOREIGNKEY:id"`
}

type CreditCard struct {
	Id     int
	Number string
	UserID string
}



func main() {
	db, _ := gorm.Open("sqlite3", "testdb.db")
	db.Exec("PRAGMA foreign_keys = ON")
	db.LogMode(true)
	db.AutoMigrate(&User{}, &CreditCard{})
	db.Model(&CreditCard{}).AddForeignKey("id", "users(id)", "RESTRICT", "RESTRICT")
```

and I look at it in db browser and I can not see the table has reference int !

however if I add // `sql:"type:text REFERENCES users(id)"` to make it look like
```
type CreditCard struct {
	Id     int
	Number string
	UserID string  `sql:"type:text REFERENCES users(id)"`
}
```

it will create the foreign key.

it is not clear, am I supposed to use sql struct tags?

**Comment by stevanusandrianta** [comment]
hi @medyagh 

there is an error in your code, you want to map the user_id as foreign_key to User table, so you need to map the `UserID` not the `ID`
`db.Model(&CreditCard{}).AddForeignKey("user_id", "users(id)", "RESTRICT", "RESTRICT")`

instead of
`db.Model(&CreditCard{}).AddForeignKey("id", "users(id)", "RESTRICT", "RESTRICT")`
