### ISSUE TITLE
Error: Commands out of sync. Did you run multiple statements at once?

### ISSUE THREAD

**Issue by pravinba9495** [go-gorm/gorm#3001]
go version: go1.14.1 darwin/amd64
Server version: 10.3.17-MariaDB MariaDB Server

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"log"
)

func main() {
	_, err := gorm.Open("mysql", "@(localhost)/test")
	if err == nil {
		log.Println("Connection to MySQL successful")
	} else {
		log.Fatal(err)
	}
}
```

I get the following error when using GORM driver. I do not get this error when using the native go-sql-driver.

![Screen Shot 2020-05-02 at 4 10 36 PM](https://user-images.githubusercontent.com/25143158/80891149-42ac7880-8c90-11ea-9c2c-57a3f6101704.png)

**Comment by pravinba9495** [comment]
To verify if this is actually true, I also installed MySQL community version 8 (not mariadb), the above code works flawlessly. The issue seems to occur only with Mariadb.

**Comment by Metrakit** [comment]
The same here, before i'm using the Psql driver without problems then now i have switched to mariadb i've also this probleme. Did you find a solution @pravinba9495  ?

**Comment by pravinba9495** [comment]
@Metrakit Hi. Upon further investigation, i figured out that the issue happens only with Mariadb V10, and not the V5.5. I recommend using mariadb-5.5 unless you absolutely need v10.

**Comment by bmknaidu555** [comment]
Hi, 
I too faced the same issue and did a lot of experiments to understand the actual reason.

1. I suggest you look into the "stats" section in PHPMyAdmin/database admin panel and monitor the actual load on your server.
2. I see that, in your example, you didn't close the connection to the database, In my case, this caused me "commands out of sync error", Because this makes connection buffer overflow.
3. Make sure close all your connections once you finished using them, or maintain connection pools.

Change your code as shown below:
======================

```
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"log"
)

func main() {
	db, err := gorm.Open("mysql", "@(localhost)/test")
	if err == nil {
		log.Println("Connection to MySQL successful")
	} else {
		log.Fatal(err)
	}
        defer func(){
             dbConn, err := db.DB()     
             dbConn.Close()   
         }
}
```

Hope this will resolve your issue....

**Comment by juancer** [comment]
Hi, I'm still having the error.
MariaDB 10.4.22, fresh install.
And I'm getting the error in the gorm.Open statement. 

Any solutions? Thanks
