### ISSUE TITLE
Query caching

### ISSUE THREAD

**Issue by pjebs** [go-gorm/gorm#306]
Is there any plans for query caching to be built in (say to redis or memcached)

Something like this: https://github.com/go-xorm/xorm

https://github.com/go-xorm/core/blob/master/cache.go

https://github.com/go-xorm/xorm-redis-cache

**Comment by GeertJohan** [comment]
Maybe the caching should be used by user design.
Something like:
```go
findUsers, err := db.Where("name <> ?", "jinzhu").PrepareFind(&users)
// users is not modified, just used for the reflection.
// findUsers is of type `PreparedFind` and only provides the methods Find() and Drop().
// Drop() de-allocates/drops the prepared statement.
findUsers.Find(&users).
```

**Comment by seriallink** [comment]
I just wrote an ETL in Go using Gorm and prepared statement will be just like heaven for this project. I'm running about 500 SQLs per second and the query cache hit rate is ridiculous low (10%).

**Comment by benguild** [comment]
Bumping this issue. Related: #1030

**Comment by benguild** [comment]
So, I want to make an important distinction here... which is that query caching of prepared SQL is one thing, and caching of query results to Redis or Memcache to avoid preparing and calling the query altogether (unless absolutely necessary) is another.

The latter can often eliminate the need for the former, but not always. **Both** are necessary for optimizations.

**Comment by benguild** [comment]
Has anyone explored this further? Prepared query caching seems to be one of the remaining performance issues I have yet to address.

**Comment by ilkerkorkut** [comment]
I built a plugin to cache `gorm` queries on Hazelcast distributed in-memory data-grid which supports basic SQL queries on its map data structure as named **[gorm-hazelcast](https://github.com/ilkerkorkut/gorm-hazelcast)**. I used gorm callbacks to handle queries and it may contain a little hacky approach because of callback handling inadequate. The released plugin has an initial version as v0.1.0. It supports CRUD operations and basic caching options. I am still working on it to complete the lack of features and do some improvements.

You can reach the project **[https://github.com/ilkerkorkut/gorm-hazelcast](https://github.com/ilkerkorkut/gorm-hazelcast)** and contribute it.

Thanks.

**Comment by pjebs** [comment]
I build this a while ago for this purpose: https://github.com/rocketlaunchr/remember-go

**Comment by pjebs** [comment]
@benguild Above is my attempt.
