### ISSUE TITLE
Is gorm supported for snowflakedb ?

### ISSUE THREAD

**Issue by praveenvaltix** [go-gorm/gorm#3562]
## Your Question

We are using GORM for managing our MySQL DBs and tables. We are also using Snowflake and until now we were using the native SQL queries. Snowflake as a SQL driver - https://github.com/snowflakedb/gosnowflake

So the question is, if we use gorm to manage our Snowflake DBs and tables, are there any potential issues that we should be aware of?

**Comment by jinzhu** [comment]
I haven't used the `Snowflake` database, maybe you can give it a try, and we also accept pull request for other databases support.

Thank you.

**Comment by omixen** [comment]
@jinzhu I am working on a snowflake driver for gorm here: https://github.com/omixen/gorm-snowflake

Some notes:
- It is still work in progress
- There is note on what features supported/supported due to Snowflake limitations
- The issue page has list of unit tests that are currently broken due to either SF limitation or one of the decision I made (e.g. not quoting/accepting case-insensitive names)
- There will be a PR going into this repo later with minor changes and skip-tests to accommodate SF.
- Unfortunately, SF is cloud based and we can't have a test environment, unless we can get an open source instance.
which I can try to ask.

Should we re open this issue?
