### ISSUE TITLE
Why uint instead of int?

### ISSUE THREAD

**Issue by frederikhors** [go-gorm/gorm#3638]
I can see that `gorm.Model` is:

```go
type Model struct {
	ID        uint `gorm:"primarykey"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt DeletedAt `gorm:"index"`
}
```

Why did you choose `uint` instead of `int`?

**Comment by frederikhors** [comment]
No answer to this?

**Comment by frederikhors** [comment]
:(

**Comment by jinzhu** [comment]
no specially reason, this sounds the most correct choice, but you can override the Model struct to use any type

**Comment by jonnjonnjo** [comment]
@jcalahorro what's the correlation between an id never being able to negative value to become a correct twice? 

it is also possible to create id with int, of which we could get the same size of the set of possible users, albeit with a negative value id

**Comment by jcalahorro** [comment]
@jonnjonnjo Of course, and mathematically it amounts to the same thing, but there is a significant difference: with `int` as an auto-incrementing ID, determining the starting value for the first element requires calculating the minimum integer value supported by the host system (assuming you want to utilize the full allowed range, which is the logical approach), whereas with `uint`, you know the minimum value is always 0.
Furthermore, if you later migrate the system, you must ensure the destination machine supports the same integer range; otherwise, you’ll have to recalculate everything.
Do you want an auto-incrementing ID that starts its counter at -2,147,483,648 or -9,223,372,036,854,775,808? Fine—go ahead and make things complicated if you like.
By convention, `uint` is used so that the first element is always 0—it’s as simple as that.
