### ISSUE TITLE
能否内置实现乐观锁？

### ISSUE THREAD

**Issue by ansoda** [go-gorm/gorm#3946]
1、期望功能
希望能内置加一个Version int64字段，和CreatedAt等类似，每次update时都会自动加上  UPDATE user SET ..., version = version + 1 WHERE id = ? AND version = ?
2、原因
原则上业务端也能子自己实现，但是有时候想提供一个通用的接口，Update（id int64， value interface{}）value既可以既可以传struct，也可以传map
如果调用方传一个map时，接口内部实现  UPDATE user SET ..., version = version + 1 WHERE id = ? AND version = ?就比较不友好，而且还得判断map中是否有version字段等等

**Comment by labulaka521** [comment]
没必要加到gorm里吧，可以自已简单封封装一下Update

**Comment by ansoda** [comment]
go没有泛型，如果自己封装gorm增加version来实现一个通用接口update，这个接口内部也需要用到反射，gorm内部也做了反射，感觉重复了

**Comment by jinzhu** [comment]
Just write a plugin for this like the soft delete one, don't think it is necessary to be integrated into GORM.  Pull request welcome if you are interested.

**Comment by Goxiaoy** [comment]
@jinzhu 

I write a plugin according to sofe-delete implementation https://github.com/Goxiaoy/gorm-concurrency
But it's better to be a built in function like other orms. And provider better support for chain function call
If this issue is still open for PR, I can request one
https://github.com/go-gorp/gorp#optimistic-locking
https://docs.microsoft.com/en-us/ef/core/modeling/concurrency?tabs=data-annotations
https://docs.jboss.org/hibernate/core/3.3/reference/en/html/transactions.html#transactions-optimistic

我根据软删除的实现写了一个乐观锁的插件
但是如果像其他Orm一样有内置的支持会比较方便链式函数调用
如果这个issue 还开放的话我可以提一个PR

**Comment by jinzhu** [comment]
Hi @Goxiaoy 

Would you like to maintain a gorm plugin like this one? https://github.com/go-gorm/soft_delete

**Comment by jinzhu** [comment]
If so, I will create a repo for you.

**Comment by Goxiaoy** [comment]
@jinzhu 
Sure, my pleasure. But it will depend on some modification on main repo

https://github.com/go-gorm/gorm/blob/74e7a9ca079ba44c4e9038088dace76726f2b69c/finisher_api.go#L106-L108

Concurrency update will run into this condition
