### ISSUE TITLE
AutoMigrate  already exists bug

### ISSUE THREAD

**Issue by fugitivers** [go-gorm/gorm#3958]
var db *gorm.DB
db, err = gorm.Open(mysql.Open(dbAddress), &gorm.Config{})

db.AutoMigrate(Camera{})
db.AutoMigrate(Sequence{})

你好，AutoMigrate报错，Error 1050: Table 'Sequences' already exists
[0.121ms] [rows:0] CREATE TABLE `Sequences` (`SequenceID` bigint AUTO_INCREMENT,`Image` longtext,`UserPwd` bigint,`Brand` bigint,`Status` bigint,`ID` longtext,`Birthday` bigint,`Sex` boolean,PRIMARY KEY (`SequenceID`))

**Comment by JonasDoe** [comment]
I've stumbled upon the same issue under these conditions:
- Using the `mysql` `Dialector`
- The table does exist already
- The gorm `Table` is set with schema name, e.g. `myschema.mytable` 
- The schema is not set in the underlying `mysql` connection

The automigration won't fail because of a missing schema (it probably accepted my dot-notation), but the `HasTable` will check whether the table `mytable` exists in the migrator's `CurrentDatabase()`, which is not `myschema` but `INFORMATION_SCHEMA`.

**Comment by priceou** [comment]
说错了不是单引号是backquote符号 `

**Comment by JonasDoe** [comment]
I just realized that details might be missed b/c the issue was already stale/closed, so I'll ping @jinzhu 
Sry for the harrassment :see_no_evil:
