### ISSUE TITLE
Statement.Clauses keep latest data

### ISSUE THREAD

**Issue by ThinkMo** [go-gorm/gorm#4177]
driver: mysql
version: 1.21.3

## Description

```
func s() []Product {
    r := []Product{}
    db.Where(map[string]interface{}{"Deleted": false}).Find(&r)
    fmt.Println(db.Statement.Clauses)
    return r
}

func main() {
    var err error
    db, err = gorm.Open(mysql.Open("root:Hello123@tcp(127.0.0.1:3306)/ops?charset=utf8mb4&parseTime=True&loc=Local"), &gorm.Config{
        NamingStrategy: schema.NamingStrategy{
            SingularTable: true,
        },
    })
    if err != nil {
        panic("failed to connect database")
    }

    // no migrate will ok   
    db = db.Set("gorm:table_options", "ENGINE=InnoDB")
    db.AutoMigrate(&Product{})

    s()
    s()
    s()
    s()
    s()
}
```

Statement.Clauses output:
map[FROM:{FROM <nil> <nil> <nil> {[] []} <nil>} SELECT:{SELECT <nil> <nil> <nil> {false [] <nil>} <nil>} WHERE:{WHERE <nil> <nil> <nil> {[{Deleted false}]} <nil>}]
map[FROM:{FROM <nil> <nil> <nil> {[] []} <nil>} SELECT:{SELECT <nil> <nil> <nil> {false [] <nil>} <nil>} WHERE:{WHERE <nil> <nil> <nil> {[{Deleted false} {Deleted false}]} <nil>}]
map[FROM:{FROM <nil> <nil> <nil> {[] []} <nil>} SELECT:{SELECT <nil> <nil> <nil> {false [] <nil>} <nil>} WHERE:{WHERE <nil> <nil> <nil> {[{Deleted false} {Deleted false} {Deleted false}]} <nil>}]

every time exec the Statement.Clauses WHERE add a cond

**Comment by jsaevitzon** [comment]
Reopening because running into same issue. Copy/pasting reproduction steps from original post 

envs := []Env{}
db.Where(map[string]interface{}{"Deleted": false}).Find(&envs)

Statement.Clauses output:
map[FROM:{FROM {[] []} } SELECT:{SELECT {false [] } } WHERE:{WHERE {[{Deleted false}]} }]
map[FROM:{FROM {[] []} } SELECT:{SELECT {false [] } } WHERE:{WHERE {[{Deleted false} {Deleted false}]} }]
map[FROM:{FROM {[] []} } SELECT:{SELECT {false [] } } WHERE:{WHERE {[{Deleted false} {Deleted false} {Deleted false}]} }]

every time exec the Statement.Clauses WHERE add a cond

**Comment by jsaevitzon** [comment]
status:open
