### ISSUE TITLE
`Exec` does not handle dollar placeholders correctly

### ISSUE THREAD

**Issue by nrnrk** [go-gorm/gorm#4307]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/312

## Description

* Seems not `Exec` supports dollar placeholder
  * Like `INSERT INTO "users" ( "id" ) VALUES ( $1 )`
* Now I am migrating V1 to V2, this kind of execution was succeeded in V1. But seems not in V2.
* Thanks in advance

**Comment by jbrockopp** [comment]
@jinzhu 

I'm experiencing a very similar problem but it is [with `Raw()`](https://pkg.go.dev/gorm.io/gorm#DB.Raw) rather [than `Exec()`](https://pkg.go.dev/gorm.io/gorm#DB.Exec) using `$` placeholders.

## Context

The queries are being ran against a Postgres instance which still uses `$` syntax for placeholders.

The query being ran looks like this:

```sql
SELECT *
FROM users
WHERE name = $1
LIMIT 1;
```

The way this query is executed in code with `gorm.io/gorm` looks like:

```go
	err := db.Raw(`SELECT * FROM users WHERE name = $1 LIMIT 1;`, "foo").Scan(myUser).Error
```

## Output

The error message returned when the above query is ran:

```
expected 1 arguments, got 0
```

And I can see from the Gorm logging output that the query provided is incorrect:

```sql
SELECT *
FROM users
WHERE name = $1$
LIMIT 1;
```

> NOTE: The extra `$` suffix for the `$1` placeholder argument.

The expected behavior is the query runs as intended without the extra `$` suffix added to the placeholder.

## Workaround

After trying some things, I found that if I update my original query to use `?` instead of `$` placeholders, everything works.

To be more clear, this query runs without issue:

```sql
SELECT *
FROM users
WHERE name = ?
LIMIT 1;
```

> NOTE: I replaced the `$1` placeholder in the original query for `?` as a placeholder

And the corresponding code to invoke it:

```go
	err := db.Raw(`SELECT * FROM users WHERE name = ? LIMIT 1;`, "foo").Scan(myUser).Error
```

**Comment by jbrockopp** [comment]
I double checked other queries we had that used to work in `V1` that no longer work in `V2` and saw the same behavior.

Another example of the bug using `$` placeholders with `Raw()`:

```sql
SELECT *
FROM repos
WHERE org = $1
AND name = $2
LIMIT 1;
```

And the way this query is executed in code with `gorm.io/gorm` looks like:

```go
	err := db.Raw(`SELECT * FROM repos WHERE org = $1 AND name = $2 LIMIT 1;`, "foo", "bar").Scan(myRepo).Error
```

I can see from the GORM logging output that the query that actually ran is incorrect:

```sql
SELECT *
FROM repos
WHERE org = $1$
AND name = $2$
LIMIT 1;
```

As mentioned above, if I swap the `$` placeholders for `?` everything works fine:

```sql
SELECT *
FROM repos
WHERE org = ?
AND name = ?
LIMIT 1;
```

And the corresponding code to invoke it:

```go
	err := db.Raw(`SELECT * FROM repos WHERE org = ? AND name = ? LIMIT 1;`, "foo", "bar").Scan(myRepo).Error
```

In case it helps anything, here are the current versions we're using of `gorm.io/gorm` from our `go.mod`:

```
	gorm.io/driver/postgres v1.0.8
	gorm.io/gorm v1.21.10
```

**Comment by jinzhu** [comment]
Hi, gorm.io/gorm only works with placeholder `?` or named argument like `@name`, e.g:

https://gorm.io/docs/advanced_query.html#Named-Argument

To use the postgres driver style, maybe use it like:

```go
sqlDB, err := db.DB()
rows, _ := sqlDB.QueryRows(`SELECT * FROM repos WHERE org = ? AND name = ? LIMIT 1;`, "foo", "bar")
defer rows.Close()

var user User
for rows.Next() {
  // ScanRows scan a row into user
  db.ScanRows(rows, &user)

  // do something
}
```

**Comment by jbrockopp** [comment]
@jinzhu while I don't agree with that implementation, I understand.

FWIW - The official Postgres documentation states that `$` placeholders are still syntactically valid:

https://www.postgresql.org/docs/current/xfunc-sql.html#XFUNC-SQL-FUNCTION-ARGUMENTS

So I'm guessing that this is likely to cause confusion in the future.

Due to the above, could I at least ask that be added to the GORM documentation?

I see no mention of `$` placeholders not being supported anywhere which is important for Postgres consumers of GORM.

I'd say at least add it to here:

https://gorm.io/docs/sql_builder.html

But also consider adding it to one of the following pages?

* https://gorm.io/docs/changelog.html#v2-0-2020-08
* https://gorm.io/docs/v2_release_note.html
