### ISSUE TITLE
DeleteInBatch()

### ISSUE THREAD

**Issue by chiahsoon** [go-gorm/gorm#4455]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/339

## Description

When deleting large amounts of items from database, `Delete()` results in too many placeholders in the prepared SQL statement. I'm hoping there could be a function similar to `CreateInBatches()` i.e. `DeleteInBatches()` to overcome this, over a manually written for-loop.

(Additionally, can consider explicitly mentioning this issue in docs/other places, because this issue may very easily go unnoticed, but just my thoughts since this is not gorm's fault!)

**Comment by huacnlee** [comment]
The Delete method that different with Create.

Delete was execute deleting with conditions in database in usually. So we design a DeleteInBatch may not usefulness.

If you have a batch of ids wants to delete. You can split the ids array for batch delete.

**Comment by chiahsoon** [comment]
Hey @huacnlee, alright thanks for the reply, that makes sense! 

I just wanted to add on and ask if this is a similar reason as to why `FindInBatches` also doesn't split up the placeholders into multiple requests in the resultant SQL query and runs into the same placeholder error?

**Comment by huacnlee** [comment]
😅 It a good question.

Before you ask, my opinion is because usually, bulk find or create will transfer a lot of data. So we must split them to reduce transmission delay.  But deletion is not required, delete is executed in database, just affects execution time.

Yes, it need in sometimes.

And then I found that looks Rails will accept this changes:

https://github.com/rails/rails/issues/22510
https://github.com/rails/rails/pull/40445

@jinzhu
