### ISSUE TITLE
can not link clickhouse

### ISSUE THREAD

**Issue by zhuyujie000** [go-gorm/gorm#5428]
clickhouse version == 20.12.4.5
![image](https://user-images.githubusercontent.com/48507102/173766144-c2948477-337e-4ee0-9f06-4c2acac58fed.png)

**Comment by zhuyujie000** [comment]
please help me.  
Sorry my English is not good enough

**Comment by a631807682** [comment]
1. If you encounter a bug in GORM, please report with the Playground Pull Request's link
[go-gorm/playground](https://github.com/go-gorm/playground)
2. Test is pass in https://github.com/go-gorm/clickhouse
https://github.com/go-gorm/clickhouse/blob/master/tests_test.go#L21
3. Of course, it may also be caused by different clickhouse server versions. You can use the specified version in docker-compose.yml to report this problem

**Comment by zhuyujie000** [comment]
I found the location of the final error, but I didn't understand what he meant. Could you please tell me a more detailed solution? Thank you!

 
![image](https://user-images.githubusercontent.com/48507102/173792159-de657a5d-71d1-4d75-b593-80b5decaf0ba.png)

**Comment by a631807682** [comment]
It means that enough data cannot be read from the connect, it may be a problem with the connection, or it may be caused by read timeout, you can try to check them
