### ISSUE TITLE
Migrate from varchar to text not work

### ISSUE THREAD

**Issue by halfcrazy** [go-gorm/gorm#5462]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
![image](https://user-images.githubusercontent.com/4113173/175779028-d3432fef-53c2-4125-8263-37287f9d8be4.png)

**Comment by tfonfara** [comment]
Unfortunately it seems that the fix of this ticket is not perfectly fine, especially this part:
```
// check type
if !field.PrimaryKey && !strings.HasPrefix(fullDataType, realDataType) {
	alterColumn = true
}
```
I was wondering why after updating gorm the auto migration was taking so long. I found that I was using type `int32` (not null) in my models, which caused the issue. While debugging I found that in [here](https://github.com/go-gorm/gorm/blob/master/migrator/migrator.go#L412) for `int32` and postgres dialect the `fullDataType` is `integer not null` and `realDataType` is `int4` which is fine in general but due to the upper code snippet it runs a migration every time for all `int32` fields.

@a631807682 is there any chance to limit this condition to the mentioned data types, as this might affect others as well.
