### ISSUE TITLE
Postgres Max Identifier length is 63 bytes

### ISSUE THREAD

**Issue by ghostsquad** [go-gorm/gorm#6098]
## GORM Playground Link

(no playground link)

## Description

Postgres has a max identifier length of 63 bytes. I see a test here that's asserting for 64 characters/bytes.

https://github.com/go-gorm/gorm/blob/master/schema/naming_test.go#L196

https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes

https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by ghostsquad** [comment]
Not stale. I don't think that a playground PR is strictly necessary here. Links to the documentation and current tested expectations have been mentioned.

**Comment by ghostsquad** [comment]
Insistent little bot...

**Comment by a631807682** [comment]
Since different databases support different lengths, we can add configuration items to schema.NamingStrategy and change the default configuration of Postgres drivers.
Contributions welcome, let me know if anyone is interested.

**Comment by alidevhere** [comment]
> Since different databases support different lengths, we can add configuration items to `schema.NamingStrategy` and change the default configuration of Postgres driver. Contributions welcome, let me know if anyone is interested.

Hii !!
Please assign this issue to me, i would love to work on it.

**Comment by alidevhere** [comment]
@a631807682 
Sorry if i sound like a fool, but this is my first contribution in this repo. And i still don't get how can we do that?
Let me explain my self what i mean

You asked to add configuration item in ```schema.NamingStrategy```
So i added ``` NamingStrategyConfig ``` [see here](https://github.com/go-gorm/gorm/pull/6196#issuecomment-1487024055) :

```
// NamingStrategy tables, columns naming strategy
type NamingStrategy struct {
	TablePrefix   string
	SingularTable bool
	NameReplacer  Replacer
	NoLowerCase   bool
	NamingStrategyConfig
}

// This struct is used to configure the behavior NamingStrategy, according to DB.
// For example, in MySQL, the maximum length of an identifier is 64 characters.
// In PostgreSQL, the maximum length of an identifier is 63 characters.
// In SQL Server, the maximum length of an identifier is 128 characters.
// In SQLite, the maximum length of an identifier is unlimited.
// In future, we may add more options to NamingStrategyConfig.
type NamingStrategyConfig struct {
	IdentifierMaxLength int
}

```

Since i have added IdentifierLength field in  [NamingStrategy](https://github.com/alidevhere/gorm/blob/issue-6098/schema/naming.go#L30)  so i had impression we would use [schema.NamingStrategy](https://github.com/go-gorm/gorm/blob/master/gorm.go#L149) to populate Identifier Length, [like this](https://github.com/alidevhere/gorm/blob/issue-6098/gorm.go#L146-L161)

```
if config.NamingStrategy == nil {
		// Set default value of IdentifierMaxLength according to the database type
		identifierMaxLength := 64
		switch dialector.Name() {
		case "mysql":
			identifierMaxLength = 64
		case "postgres":
			identifierMaxLength = 63
		case "sqlite":
			identifierMaxLength = 64
		case "sqlserver":
			identifierMaxLength = 128
		}

		config.NamingStrategy = schema.NamingStrategy{NamingStrategyConfig: schema.NamingStrategyConfig{IdentifierMaxLength: identifierMaxLength}}
	}

``` 

You said its not recommended to do it on the basis of  dialector name. ok got it !! 👍🏻  
And you told me that We can use ``` Apply()``` 


Now my question is: how can we pass identifier length to Apply according to choosen dialector ?? (because apparently driver implementing interface dialector is passed, and we need to pass Identifeir Lengths to NamingStrategy according to DB)

How we know we need to initialize identifierMaxLength as 63,64 or 128 if we don't kknow the DB.

```
if d, ok := dialector.(interface{ Apply(*Config) error }); ok {
		if err = d.Apply(config); err != nil {
			return
		}
	}

```

### I know you are busy, but your little help will push me to complete this task, Thanks 😄

**Comment by a631807682** [comment]
> Now my question is: how can we pass identifier length to Apply according to choosen dialector ?? (because apparently driver implementing interface dialector is passed, and we need to pass Identifeir Lengths to NamingStrategy according to DB)

> How we know we need to initialize identifierMaxLength as 63,64 or 128 if we don't kknow the DB.

We just need to set a default value, and then override it through Apply api in each driver

**Comment by myusko** [comment]
@a631807682 Does it make sense to close the issue? since it was addressed in the https://github.com/go-gorm/gorm/pull/6337
