### ISSUE TITLE
Preload don't works with spec ID in Model()

### ISSUE THREAD

**Issue by ITIFSMTH** [go-gorm/gorm#6582]
```
type Message struct {
	gorm.Model
	Attachment Attachment
}

type Attachment struct {
	gorm.Model
	MessageID  uint
}
```

Now, if you try this:

```
db.Model(&models.Message{}).Where(&models.Message{
	Model: gorm.Model{
		ID: 1,
	},
}).Preload("Attachment")).First(&message)
```

All works perfectly, and Attachment is preloaded

But if you try this:

```
db.Model(&models.Message{
        Model: gorm.Model{
		ID: body.MessageID,
	},
}).Preload("Attachment").First(&message)
```

Message will finded, but attachment will not preload. Is it a bug or feature?

**Comment by twocs** [comment]
The `Model` helps to determine the table but is not used to limit the query.

Your first query
```
db.Model(&models.Message{}).Where(&models.Message{
	Model: gorm.Model{
		ID: 1,
	},
}).Preload("Attachment")).First(&message)
```
This results in the query 
```SELECT * FROM `messages` WHERE `messages`.`id` = 1 AND `messages`.`deleted_at` IS NULL ORDER BY `messages`.`id` LIMIT 1```

Your second statement 
```
db.Model(&models.Message{
        Model: gorm.Model{
		ID: body.MessageID,
	},
}).Preload("Attachment").First(&message)
```
This results in the query
```SELECT * FROM `messages` WHERE `messages`.`deleted_at` IS NULL ORDER BY `messages`.`id` LIMIT 1```
This is as expected because the model determines the table but not the row of the table. It will return record ID: 1, not ID: body.MessageID.

Use a `Where` clause or put the `ID` into the finaliser like `First(&message, body.MessageID)`.
