### ISSUE TITLE
并发场景下，使用raw方法执行sql会报错expected 2 arguments, got 4; invalid value, should be pointer to struct or slice;

### ISSUE THREAD

**Issue by Zzy413341422** [go-gorm/gorm#6646]
.Raw("select sum(points) as cnt from xx where task_id in ? ", taskIDList).Find(&sum).Error

**Comment by ivila** [comment]
First, its recommended to give a reproduction steps instead of just a one line broken code, it's hard for others to investigate and just wasting time.

you miss some important information in your issue due to "missing reproduction steps", for example:
1, what version of gorm you are using
2, what version of golang you are using
3, what is the "concurrency scenario"
 for example, I have a concurrent demo codes:
```golang
// go version: go1.21.0 linux/amd64
// gorm.io/gorm v1.25.5
// gorm.io/driver/mysql v1.5.2
func runConcurrency(db *gorm.DB, concurrency int, repeatTimes int) {
        wg := sync.WaitGroup{}
        var idList = []uint64{1, 2, 3}
        for i := 0; i < concurrency; i++ {
                wg.Add(1)
                go func(id int) {
                        defer wg.Done()

                        var sum int64
                        for j := 0; j < repeatTimes; j++ {
                                err := db.Raw("select count(1) + 1 as cnt from product where id in ?", idList).Find(&sum).Error
                                if err != nil {
                                        panic(fmt.Sprintf("err happend at id %d, err is %v", id, err))
                                }
                        }
                }(i)
        }
        wg.Wait()
}
```
this code will run very well without any error.

I suspect you are using an older version of gorm(or even the jinzhu.com/gorm), and with that version, you will need to use other functions to achieve you goal, just rewrite your codes to the following:
```golang
// 1, add brackets around the question mark when using in query, to fix the error of "expected 2 arguments, got 4"
// 2, use the Count method instead of Find method, to fix the error of "invalid value, should be pointer to struct or slice"
.Raw("select sum(points) as cnt from xx where task_id in (?) ", taskIDList).Count(&sum).Error
```

**Comment by ivila** [comment]
@Zzy413341422 if the issue had been fixed, please close it, thanks for the effort.
