### ISSUE TITLE
Add database backend support for CockroachDB

### ISSUE THREAD

**Issue by ERnsTL** [go-gorm/gorm#740]
While in first development stages, the design, features and algorithms of [Cockroach](https://github.com/cockroachdb/cockroach) look highly promising. Open source, scalable, geo-replicated, ACID compliant. It is inspired by the Google Spanner database system. It is better than the FoundationDB supported by GORM, which was taken down by Apple.

Cockroach looks like a successor to FoundationDB. Also written in Go and implementing SQL, CockroachDB would be a great match and good addition for GORM.

See here:
- [Cockroach repository](https://github.com/cockroachdb/cockroach)
- [CockroachDB: A Scalable, Geo-Replicated, Transactional Datastore](http://www.infoq.com/news/2014/08/CockroachDB)
- [CockroachDB: Ultimate in Database Survival](http://www.informationweek.com/big-data/software-platforms/cockroachdb-ultimate-in-database-survival/d/d-id/1320700)

Please add database connector for CockroachDB.

**Comment by Ozzadar** [comment]
+ 1

Any news on this? Is it planned? Just wondering :)

**Comment by joeblew99** [comment]
i am using cockroach and its amazing.. Still some loose edges but really impressive compared to postresql.
So yes +1 so i can use it with GORM.

**Comment by d4l3k** [comment]
I'm working on implementing cockroach here: https://github.com/d4l3k/gorm

There are a number of things that make it hard to integrate with gorm:
* Since it's a distributed database there is no auto increment option. Instead, it has `experimental_unique_int()`, which generates a [random uint64](https://github.com/cockroachdb/cockroach/issues/2513). This means that you can't have shorter primary keys since it truncates the key and thus will be less random (if short enough, 1).
* Cockroach doesn't support "RETURNING" statements. So creating a new entry involves a select statement to make a new unique id, and then a second to insert the record.
* Cockroach client [returns sql.ErrNoRows](https://github.com/cockroachdb/cockroach/pull/2614) for operations that doesn't modify rows.
* null has to be typed when being set (`null::int`).
* strings aren't automatically cast into dates

I've gotten a lot of the tests passing, but there's still quite a few errors that need to be taken care of.

**Comment by joeblew99** [comment]
The cockroach guy will be open to helping I suspect

**Comment by Ozzadar** [comment]
@joeblew99 Are you interfacing with Cockroach through golang? If so, can you point me to some reference documents to get started?

In the cockroach/client repo it says to use a postgres driver, is this how it is to be done at the moment?

Thanks :)

(I would have DM'd you but github for some reason doesn't have this feature.)

**Comment by joeblew99** [comment]
Yep that's exactly it.
Use postresql driver and your good.
It's awesome. Later I expect they will extend beyond that but that's for
future stuff.

Joe

**Comment by Ozzadar** [comment]
Thanks!

I hear you've been talking to faddat. I'm the guy working with him. If you have time to chat get in contact through him, I'd like to pick your brain :)

-Paul

**Comment by joeblew99** [comment]
Hey Paul,

Sure just hook me up, as I am not sure I know his contacts. Happy to chat / help.

**Comment by acim** [comment]
https://www.cockroachlabs.com/docs/build-a-go-app-with-cockroachdb-gorm.html

**Comment by koalalorenzo** [comment]
Hello, any update on this? :)

**Comment by jordanlewis** [comment]
GORM and CockroachDB seem to interoperate just fine to me. A common sticking point is that you need to create the database ahead of time, just like you would in PostgreSQL. The example you link contains instructions to create the database - if you do that first, things will work just fine.

Thanks! Let me know if you have more issues, we really want to make sure CockroachDB and GORM work well together.

**Comment by awoods187** [comment]
We think GORM works pretty well with CockroachDB. Is there anything else you think needs to be added on your end or ours?
