### ISSUE TITLE
AutoMigrate not create table

### ISSUE THREAD

**Issue by vlegio** [go-gorm/gorm#84]
If table not exist AutoMigrate not create table

**Comment by edufszoop** [comment]
I have the following struct:

type ApiSettings struct {
	id            int `gorm:"column:id" json:"_id"`
	uid           uuid.Generator `gorm:"column:uid;index" json:"uid"`
	tableName     string `gorm:"column:tableName" json:"tableName"`
	key           string `gorm:"column:key" json:"key"`
	value         string `gorm:"column:value" json:"value"`
	dataType      string `gorm:"column:dataType" json:"dataType"`
	isDeleted     int `gorm:"column:isDeleted" json:"isDeleted"`
	canUpdate     int `gorm:"column:canUpdate" json:"canUpdate"`
	version       int `gorm:"column:version" json:"version"`
	compression   int `gorm:"column:compression" json:"compression"`
	dflag         int `gorm:"column:dflag" json:"dflag"`
	createdAt     time.Time `gorm:"column:createdAt" json:"createdAt"`
	updatedAt     time.Time `gorm:"column:updatedAt" json:"updatedAt"`
}

For some reason when I run 
`db.Debug().AutoMigrate(&ApiSettings{})`, 
I got the following error:
`Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1` 

The SQL printed is:
`CREATE TABLE `ApiSettings` ( )`

As you can see, gorm is ignoring my strutct. 

I'm new to Gorm. My first time using it.

**Comment by EmpireJones** [comment]
@edufszoop I just ran into this same issue; your fields need to be exported (upper case), otherwise gorm won't see them.

**Comment by raghvendra1218** [comment]
@everyone : I spent half an hour in figuring out, why my table columns are not being created by GORM, since I created the DB and everything, I defined the structure, until i came to this last very comment of this Thread and seen the comment of @EmpireJones , very important thing which Gorm follows that the variable or schema attributes inside your structure should be starting with Capital Letter otherwise Gorm will not recognize them. I will try to articulate this more for users who run into this issue and will look this comment in this thread.
My structure was(before reading this comment of @EmpireJones ):
type User struct {
	gorm.Model
	name  string `json:"Name"`
	email string `json:"Email"`
}
and I was expecting name and email columns to be created when i first time run the db.AutoMigrate(&User), but when querying in DB I could just see four columns under user table :->
1. Id
2. created_at
3. updated_at
4. deleted_at
and I was just confused why those name and email column are not there.
my User Struct after reading the above comment(which resolved this issue)
type User struct {
	gorm.Model
	Name  string `json:"Name"`
	Email string `json:"Email"`
}
P.S. - Notice the Capital letter 'N' in Name and 'E' in Email .
In Nut-shell all the fields should start with Capital letter in order for Gorm to recognize them during Schema creation. Hope this helps. Thanks @EmpireJones
